# Tensors
A tensor is a genralization of vectors or matrices and can be seen as a multidimensional array. A tensor can have a variable no. of axis.

* A vector is a one-dimensional tensor or first order tensor.
* A matrix is a two-dimensional tensor or second order tensor.

A 3 X 3 X 3 tensor can be written as 
$$T = \begin{pmatrix}t_{1,1,1} & t_{1,2,1} & t_{1,3,1} \\
t_{2,1,1} & t_{2,2,1} & t_{2,3,1} \\
t_{3,1,1} & t_{3,2,1} & t_{3,3,1} 
\end{pmatrix} , \begin{pmatrix}t_{1,1,2} & t_{1,2,2} & t_{1,3,2} \\
t_{2,1,2} & t_{2,2,2} & t_{2,3,2} \\
t_{3,1,2} & t_{3,2,2} & t_{3,3,2} 
\end{pmatrix} , \begin{pmatrix}t_{1,1,3} & t_{1,2,3} & t_{1,3,3} \\
t_{2,1,3} & t_{2,2,3} & t_{2,3,3} \\
t_{3,1,3} & t_{3,2,3} & t_{3,3,3} 
\end{pmatrix}$$

In [1]:
import numpy as np

In [6]:
# Define a 3 X 3 X 3 tensor
T = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
])
print(T)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [7]:
T.shape

(3, 3, 3)

In [9]:
# Element wise Addition in tensors
A = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
])

B = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
])

print(A + B)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[20 22 24]
  [26 28 30]
  [32 34 36]]

 [[38 40 42]
  [44 46 48]
  [50 52 54]]]


In [10]:
# Element wise Subtraction in tensors
print(A - B)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [11]:
# Element wise Multiplication in tensors (Tensor Hadamard Product)
print(A * B)

[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[100 121 144]
  [169 196 225]
  [256 289 324]]

 [[361 400 441]
  [484 529 576]
  [625 676 729]]]


In [12]:
# Element wise Division in tensors
print(A / B)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


## Tensor Product 
A tensor product can be done not just on tensors but also on vectors and matrices.

A tensor product for vector 
$$A = \begin{pmatrix}a_1 \\
a_2 \end{pmatrix}$$
$$B = \begin{pmatrix}b_1 \\
b_2 \end{pmatrix}$$

A tensor product C would be 
$$C = \begin{pmatrix}a_1 X \begin{pmatrix}b_1 \\
b_2 \end{pmatrix}\\
a_2 X \begin{pmatrix}b_1 \\
b_2 \end{pmatrix}\\
\end{pmatrix}$$
$$C = \begin{pmatrix}a_1 X b_1 & a_1 X b_2 \\
a_2 X b_1 & a_2 X b_2
\end{pmatrix}$$


Similary for matrix, a tensor product would be 
$$A = \begin{pmatrix}a_{1,1} & a_{1,2} \\
a_{2,1} & a_{2,2} \end{pmatrix}$$
$$B = \begin{pmatrix}b_{1,1} & b_{1,2} \\
b_{2,1} & b_{2,2} \end{pmatrix}$$

$$C = \begin{pmatrix}a_{1,1} X \begin{pmatrix}b_{1,1} & b_{1,2} \\
b_{2,1} & b_{2,2} \end{pmatrix} & 
a_{1,2} X \begin{pmatrix}b_{1,1} & b_{1,2} \\
b_{2,1} & b_{2,2} \end{pmatrix} \\
a_{2,1} X \begin{pmatrix}b_{1,1} & b_{1,2} \\
b_{2,1} & b_{2,2} \end{pmatrix} & 
a_{2,2} X \begin{pmatrix}b_{1,1} & b_{1,2} \\
b_{2,1} & b_{2,2} \end{pmatrix}
\end{pmatrix}
$$

$$C = \begin{pmatrix}a_{1,1} X b_{1,1} & a_{1,1} X b_{1,2} & a_{1,2} X b_{1,1} & a_{1,2} X b_{1,2} \\
a_{1,1} X b_{2,1} & a_{1,1} X b_{2,2} & a_{1,2} X b_{2,1} & a_{1,2} X b_{2,2} \\
a_{2,1} X b_{1,1} & a_{2,1} X b_{1,2} & a_{2,2} X b_{1,1} & a_{2,2} X b_{1,2} \\
a_{2,1} X b_{2,1} & a_{2,1} X b_{2,2} & a_{2,2} X b_{2,1} & a_{2,2} X b_{2,2}
\end{pmatrix}
$$

In [14]:
A = np.array([1,2])
B = np.array([3,4])
print(np.tensordot(A, B, axes = 0))

[[3 4]
 [6 8]]


In [16]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[1,2],
              [3,4]])

C = np.tensordot(A, B, axes = 0)
print(C)

[[[[ 1  2]
   [ 3  4]]

  [[ 2  4]
   [ 6  8]]]


 [[[ 3  6]
   [ 9 12]]

  [[ 4  8]
   [12 16]]]]


In [17]:
C.shape

(2, 2, 2, 2)