# Matrix Decomposition (Matrix Factorization)
A matrix decomposition is a way of reducing the matrix into its constituent parts. Two simple ways of decomposition are :-

1. __LU decomposition__ :- This is for the square matrix and decomposes the matrix in 2 components L and U.
$$A = L U$$
where L is the lower traingle matrix and U is the upper traingle matrix.

LU decomposition is found using an interative numerical process and can fail for those matrices that cannot be decomposed. Another variation of the decomposition is called LUP decomposition. 
$$A = L\ U\ P$$

The rows of the parent matrix are re-ordered to simplify the decomposition process and the additional P matrix specifies a way to permute the result or return the result to the original order. There are also other variations of the LU.

In [21]:
import numpy as np
import scipy.linalg as lin
from sklearn.decomposition import TruncatedSVD

In [4]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

# factorize 
P, L, U = lin.lu(A)
print(P)
print(L)
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]


In [5]:
# We can reconstruct the matrix A
print(P.dot(L).dot(U))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


2. __QR Decomposition__ :- 
The QR decomposition is for n X M matrices and decomposes a matrix into Q and R components.
$$A = Q\ R$$
where Q is a matrix of size m X m and R is an upper traingle matrix with size m X n. The use of QR is not limited to square matrix.

QR decomposition is found using an interative numerical process and can fail for those matrices that cannot be decomposed. 

In [10]:
A = np.array([[1,2],
              [3,4],
              [5,6]])

# factorize 
Q, R = lin.qr(A, mode = "full")
print(Q)
print(R)

[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]


In [11]:
# We can reconstruct the matrix A
print(Q.dot(R))

[[1. 2.]
 [3. 4.]
 [5. 6.]]


3. __Cholesky Decomposition__ :- 
The Cholesky decomposition is for square symmetric matrices where all values are greater than zero, so-called positive definite matrices. The decomposition can be written as $$A = L\ L^T$$
where L is the lower triangular matrix and $L^T$ is the transpose of L. We can also write the decompose as $$A = U^T\ U$$ where U is the upper triangular matrix.

In [17]:
A = np.array([[2,1,1],
              [1,2,1],
              [1,1,2]])
L = lin.cholesky(A, lower = True)
print(L)

[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]


In [18]:
# We can reconstruct the matrix A
print(L.dot(L.T))

[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


# Eigendecomposition
This decomposes a square matrix into eigenvectors and eigenvalues. 

__Eigenvector__ :- A vector is an eigenvector of a matrix if it satisfies the following equation. 
$$A\ v = \lambda\ v $$
where v is the eigenvector and $\lambda$ is the eigen value. Eigenvectors are unit vectors, which means that their length or magnitude is equal to 1.0.

__Eigenvalues__ :- Eigenvalues are coefficients applied to eigenvectors that give the vectors their length or magnitude.

A matrix could have one eigenvector and eigenvalue for each dimension of the parent matrix. Not all square matrices can be decomposed into eigenvectors and eigenvalues, and some can only be decomposed in a way that requires complex numbers.

The parent matrix can be shown as a product of the eigenvectors and eigenvalues. $$A = Q\ \Lambda\ Q^T$$
where Q is a matrix comprised of eigenvectors and $\Lambda$ is the diagonal matrix comprised of eigenvalues.


In [20]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

# Eigendecomposition
values, vectors = np.linalg.eig(A)
print(values)
print(vectors)

[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


We can confirm if a vector is an eigenvector or not by using $A\ v = \lambda\ v $

In [25]:
A.dot(vectors[:,0])

array([ -3.73863537,  -8.46653421, -13.19443305])

In [26]:
values[0] * vectors[:,0]

array([ -3.73863537,  -8.46653421, -13.19443305])

In [32]:
# We can reconstruct the matrix as 
Q = vectors # matrix comprised of eigen vectors
L = np.diag(values) # create a diagonal matrix with eigenvalues.
R = np.linalg.inv(Q)

B = Q.dot(L).dot(R)
print(B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# Singular Value Decomposition
SVD decomposes a matrix such that
$$A = U\ \Sigma\ V^T$$

A is the n X m matrix that we wish to decompose. U is and m X m matrix (columns of U are called left-singular vectors of A), $\Sigma$ is an m X n matrix ( the diagonal of this matrix are called singular values of A) and V is a n X n matrix (columns of V are called right-singular vectors of A). 

In [36]:
A = np.array([
  [1, 2],
  [3, 4],
  [5, 6]])

# Decomposition of A
U,s,V = lin.svd(A)
print(U)
print(s)
print(V)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [43]:
# Reconstruct the matrix
Sigma = np.zeros((A.shape[0], A.shape[1])) # this step is only require for non-square matrix
Sigma [:A.shape[1], :A.shape[1]] = np.diag(s) # assigning singular values to diagonal

B = U.dot(Sigma.dot(V))
print(B)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


## Pseudoinverse
Also known as Generalized Inverse. It can be calculated even for the non-square metrix as well. It is denoted as $A^+$. 
$$A^+ = V\ D^+\ U^T$$
where $D^+$ = Generalised inverse of $\Sigma$ (diagonal matrix). U and V are same as in SVD. 
If $$\Sigma = \begin{pmatrix} S_{1,1} & 0 & 0 \\
0 & S_{2,2} & 0\\
0 & 0 & S_{3,3}
\end{pmatrix}$$

$$D^+ = \begin{pmatrix} \frac{1}{S_{1,1}} & 0 & 0 \\
0 & \frac{1}{S_{2,2}} & 0\\
0 & 0 & \frac{1}{S_{3,3}}
\end{pmatrix}$$


In [4]:
A = np.array([
  [0.1, 0.2],
  [0.3, 0.4],
  [0.5, 0.6],
  [0.7, 0.8]])

# Calculating pseudoinverse
B = np.linalg.pinv(A)
print(B)

[[-1.00000000e+01 -5.00000000e+00  9.07607323e-15  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


In [9]:
#Calculating pseudoinverse using SVD.
U,s,V = lin.svd(A)
d = 1/s

# Calculating the D matrix with inverse of singular value
D = np.zeros(A.shape)
D[:A.shape[1], :A.shape[1]] = np.diag(d)

B = V.T.dot(D.T).dot(U.T)
print(B)

[[-1.00000000e+01 -5.00000000e+00  9.07607323e-15  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


## Dimensionality Reduction
We can use SVD to reduce the data with a large number of features to a smaller subset of features that are most relevant to the prediction problem.

To do this we use SVD on the original data and select the top largest singular values in $\Sigma$. These columns
can be selected from $\Sigma$ and rows can be selected from $V^T$.

An approximation B of the original vector can be written as $$B = U\ \Sigma_k\ V_k^T$$

In practice, we can retain and work with a descriptive subset of the data called T. This is a dense summary of the matrix or a projection.

$$T = U\ \Sigma_k$$
Further, this transform can be calculated and applied to the original matrix A as well as other similar matrices.
$$T = A\ V_k^T$$

In [15]:
A = np.array([list(range(1,11)), list(range(11,21)), list(range(21,31))])
U,s,V = lin.svd(A)

Sigma = np.zeros((A.shape[0], A.shape[1]))
Sigma [:A.shape[0], :A.shape[0]] = np.diag(s)

#dimension to be reduced to
k = 2
Sigma = Sigma[:, :k]
V = V[:k,:]

#Reconstruct the original matrix
B = U.dot(Sigma.dot(V))
print(B)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]


In [19]:
# dense summary of the matrix or a projection.
B = U.dot(Sigma)
print(B)

T = A.dot(V.T)
print(T)

[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


In [22]:
# Dimension reduction using sklearn
svd = TruncatedSVD(n_components = 2)
svd.fit(A)

print(svd.transform(A))

[[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]
