# Matrix Decomposition (Matrix Factorization)
A matrix decomposition is a way of reducing the matrix into its constituent parts. Two simple ways of decomposition are :-

1. __LU decomposition__ :- This is for the square matrix and decomposes the matrix in 2 components L and U.
$$A = L U$$
where L is the lower traingle matrix and U is the upper traingle matrix.

LU decomposition is found using an interative numerical process and can fail for those matrices that cannot be decomposed. Another variation of the decomposition is called LUP decomposition. 
$$A = L\ U\ P$$

The rows of the parent matrix are re-ordered to simplify the decomposition process and the additional P matrix specifies a way to permute the result or return the result to the original order. There are also other variations of the LU.

In [1]:
import numpy as np
import scipy.linalg as lin

In [4]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

# factorize 
P, L, U = lin.lu(A)
print(P)
print(L)
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]


In [5]:
# We can reconstruct the matrix A
print(P.dot(L).dot(U))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


2. __QR Decomposition__ :- 
The QR decomposition is for n X M matrices and decomposes a matrix into Q and R components.
$$A = Q\ R$$
where Q is a matrix of size m X m and R is an upper traingle matrix with size m X n. The use of QR is not limited to square matrix.

QR decomposition is found using an interative numerical process and can fail for those matrices that cannot be decomposed. 

In [10]:
A = np.array([[1,2],
              [3,4],
              [5,6]])

# factorize 
Q, R = lin.qr(A, mode = "full")
print(Q)
print(R)

[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]


In [11]:
# We can reconstruct the matrix A
print(Q.dot(R))

[[1. 2.]
 [3. 4.]
 [5. 6.]]


3. __Cholesky Decomposition__ :- 
The Cholesky decomposition is for square symmetric matrices where all values are greater than zero, so-called positive definite matrices. The decomposition can be written as $$A = L\ L^T$$
where L is the lower triangular matrix and $L^T$ is the transpose of L. We can also write the decompose as $$A = U^T\ U$$ where U is the upper triangular matrix.

In [17]:
A = np.array([[2,1,1],
              [1,2,1],
              [1,1,2]])
L = lin.cholesky(A, lower = True)
print(L)

[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]


In [18]:
# We can reconstruct the matrix A
print(L.dot(L.T))

[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
