# Vector

In [2]:
from math import inf
import numpy as np
import numpy.linalg as lin

In [2]:
# Define a array
v = np.array([2,5,7])
print(v)

[2 5 7]


In [3]:
# Addition in vector 
v2 = np.array([1,3,6])
print(v + v2)

[ 3  8 13]


In [4]:
# Subtraction of vector 
print(v - v2)

[1 2 1]


In [5]:
# Multiplication of vector
print(v * v2)

[ 2 15 42]


In [6]:
# Division of vector
print(v / v2)

[2.         1.66666667 1.16666667]


In [7]:
# Dot product
v.dot(v2)

59

In [8]:
# Vector - scalar multiplication
print(v * 0.5)

[1.  2.5 3.5]


# Vector Norm

The length of the vector.

* $L^1$ norm :- sum of the absolute values of the vector.
* $L^2$ norm :- square root of the sum of the square of the values of the vector.
* Max norm :- maximum of the values of the vector.

In [11]:
# L1 norm 
lin.norm(v,1)

14.0

In [12]:
# L2 norm
lin.norm(v,2)

8.831760866327848

In [16]:
# Max norm
lin.norm(v, inf)

7.0

# Matrix 
A matrix is a two-dimensional array of scalars with one or more columns and one or more rows.

In [19]:
# Defining a matrix
A = np.array([[1,2,3],[3,4,5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [20]:
# Addition of Matrix
B = np.array([[1,2,3],[3,4,5]])
print(A + B)

[[ 2  4  6]
 [ 6  8 10]]


In [21]:
# Subtraction of Matrix
print(A - B)

[[0 0 0]
 [0 0 0]]


In [22]:
# Multiplication by element in Matrix
print(A * B)

[[ 1  4  9]
 [ 9 16 25]]


In [23]:
# Division of Matrix
print(A / B)

[[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
# Matrix Multiplication
A = np.array([
    [1,2],
    [3,4],
    [5,6]])

B = np.array([
    [1,2],
    [3,4]])

print(A.dot(B))

[[ 7 10]
 [15 22]
 [23 34]]


In [25]:
# Another way of matrix multiplication
print(A @ B)

[[ 7 10]
 [15 22]
 [23 34]]


In [26]:
# Matrix and vector multiplication
v = np.array([2,4])
print(A.dot(v))

[10 22 34]


In [27]:
# Matrix and scalar multiplication
print(A * 0.5)

[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


## Types of Matrix
### 1. Square Matrix :-
The no. of rows are equal to no. of columns

### 2. Symmetric Matrix :-
A square matrix where top right angle is same as the lower right angle.

### 3. Triangle Matrix :-
A triangular matrix is a type of square matrix that has all values in the upper-right or lower-left of the matrix with the remaining elements filled with zero values.

In [28]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
# lower traingle matrix
print(np.tril(A))

[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [31]:
# Upper traingle matrix
print(np.triu(A))

[[1 2 3]
 [0 5 6]
 [0 0 9]]


### 4. Diagonal Matrix :-
A square matrix where values other than the main diagonal are zero.

In [32]:
# Diagonal Vector
print(np.diag(A))

[1 5 9]


In [33]:
print(np.diag(np.diag(A)))

[[1 0 0]
 [0 5 0]
 [0 0 9]]


### 5. identity Matrix :- 
A identity matrix is a square matrix that do not change the vector when multiplied.

In [34]:
# Define a identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 6. Orthogonal Matrix :-
Two vectors are orthogonal when their dot product is zero. If the length of the vector is 1 then they are called orthonormal because they are both orthogonal and normal.

An orthogonal matrix is a type of square matrix whose columns and rows are orthonormal
unit vectors.
$$Q . Q^T = I$$
$$Q^T = Q^{-1} $$
Orthogonal matrices are used a lot for linear transformations.

In [37]:
# A coordinate reflection matrix
A = np.array([[1,0],[0,-1]])
print(A)

[[ 1  0]
 [ 0 -1]]


In [41]:
# Inverse of A
print(lin.inv(A))

[[ 1.  0.]
 [-0. -1.]]


In [40]:
# Transpose of A
print(A.T)

[[ 1  0]
 [ 0 -1]]


In [42]:
print(A.dot(A.T))

[[1 0]
 [0 1]]


A is an orthogonal matrix.

## Matrix Operations

In [3]:
# Transpose of a matrix
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [4]:
# Inverse of a Matrix
print(lin.inv(A))

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


### Trace of a matrix :-
Sum of the elements of the main diagonal of the square matrix.

In [5]:
print(np.trace(A))

15


### Determinant
The determinant of a square matrix is a scalar representation of the volume of the matrix. More specifically, the determinant of a matrix A tells you the volume of a box with sides given by rows of A.

In [6]:
print(lin.det(A))

-9.51619735392994e-16


### Rank of a Matrix :-
No. of linearly indepenent rows and columns in a matrix.

In [7]:
print(lin.matrix_rank(A))

2
