# Vector

In [15]:
from math import inf
import numpy as np
import numpy.linalg as lin

In [2]:
# Define a array
v = np.array([2,5,7])
print(v)

[2 5 7]


In [3]:
# Addition in vector 
v2 = np.array([1,3,6])
print(v + v2)

[ 3  8 13]


In [4]:
# Subtraction of vector 
print(v - v2)

[1 2 1]


In [5]:
# Multiplication of vector
print(v * v2)

[ 2 15 42]


In [6]:
# Division of vector
print(v / v2)

[2.         1.66666667 1.16666667]


In [7]:
# Dot product
v.dot(v2)

59

In [8]:
# Vector - scalar multiplication
print(v * 0.5)

[1.  2.5 3.5]


# Vector Norm

The length of the vector.

* $L^1$ norm :- sum of the absolute values of the vector.
* $L^2$ norm :- square root of the sum of the square of the values of the vector.
* Max norm :- maximum of the values of the vector.

In [11]:
# L1 norm 
lin.norm(v,1)

14.0

In [12]:
# L2 norm
lin.norm(v,2)

8.831760866327848

In [16]:
# Max norm
lin.norm(v, inf)

7.0

# Matrix 
A matrix is a two-dimensional array of scalars with one or more columns and one or more rows.

In [19]:
# Defining a matrix
A = np.array([[1,2,3],[3,4,5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [20]:
# Addition of Matrix
B = np.array([[1,2,3],[3,4,5]])
print(A + B)

[[ 2  4  6]
 [ 6  8 10]]


In [21]:
# Subtraction of Matrix
print(A - B)

[[0 0 0]
 [0 0 0]]


In [22]:
# Multiplication by element in Matrix
print(A * B)

[[ 1  4  9]
 [ 9 16 25]]


In [23]:
# Division of Matrix
print(A / B)

[[1. 1. 1.]
 [1. 1. 1.]]
